### PR TITLE
Constructor fetch

### PR DESCRIPTION
**Pull request by matthewwrobel**
Q&A module:

-refactored to fetch data from constructor
-refactored to fetch from server less frequently
-implemented questions list
-implemented answers list
-implemented answer sorting
-implemented date formatting
-implemented answerer name formatting

@alizehrehman @tchitrakorn thanks in advance for your time and your feedback!

### CODE REVIEW

**Comment by tchitrakorn** [comment]
Hi @matthewwrobel, looks fantastic! Quick question before merging, in your AnswersList component, are we eventually going to move away from componentDidMount or is this a deliberate technical decision?

**Comment by matthewwrobel** [comment]
> Hi @matthewwrobel, looks fantastic! Quick question before merging, in your AnswersList component, are we eventually going to move away from componentDidMount or is this a deliberate technical decision?

Thanks so much for looking at all that! I plan to re-factor--that was like my quick first-draft to get it working. Do you suggest breaking that stuff out into more modular functions? That seems like a good idea.

**Comment by matthewwrobel** [comment]
@tchitrakorn now i'm realizing this should all be in the constructor function, right? haha!

**Comment by tchitrakorn** [comment]
Hi @matthewwrobel, quite frankly I'm still unclear about transitioning from componentDidMount to constructor, but my understanding from yesterday's lecture is that we may have to do it eventually. I do not mind merging what you have right now while you work on refactoring if you think that is best. Breaking stuff into modular functions seems like something that you could do later when time permitted. Let me know!

**Comment by matthewwrobel** [comment]
@tchitrakorn sounds good. Will refactor later for sure. I'll go ahead and merge.

**Pull request merged**
