### PR TITLE
Update product overview comp

### PR DESCRIPTION
**Pull request by alizehrehman**
- Split ProductOverview component into two components for modularity: OverviewDescription & OverviewFeatures
- Rendered slogan, description, and features with checkmarks
- Updated CSS to match grid formattting

### CODE REVIEW

**Comment by alizehrehman** [comment]
@jabrake @matthewwrobel Can you please review my pull request? Thank you!

**Review by jabrake — APPROVED** [review]
This all looks good! I noticed the babel.config.js file was deleted, there's some updates to the webpack.config.js and a new bundle.js.LICENSE.txt (unless I missed this one before). I'm guessing we'll all be good with these updates?

**Comment by jabrake** [comment]
Oh also - I know you have a CSS file in there (awesome!), not sure if Tatt's PR has the CSS file as well, so let's just check once we merge them all that we don't have files in different places (not sure where she added her CSS file)

**Comment by alizehrehman** [comment]
@jabrake It should all work the same way. No new modules were added (if they were during the debugging process, I removed them). If we run into issues, thankfully we can always bring back the original config files!

**Pull request merged**
